apiVersion: batch/v1
kind: Job
metadata: 
  name: olamundo-job
spec:
  template:
    spec:
      containers:
        - name: container-olamundo
          image: ubuntu:22.04
          command: ["/bin/sh", "-c"]
          args: ["sleep 15 ; /bin/echo Olá, Mundo!"]
      restartPolicy: Never
  backoffLimit: 3