apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: airportnames
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: airportnames
  minReplicas: 2
  maxReplicas: 40
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80